naiteck:
  config:
    mail: jiangxuchen_12@126.com
    from: jiangxuchen521@gmail.com

knife4j:
  enable: false
  basic:
    enable: true
    username: admin
    password: admin
  setting:
    enableFooter: false

spring:
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password:    # 密码（默认为空）
      timeout: 6000ms  # 连接超时时长（毫秒）
      lettuce:
        pool:
          max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 10      # 连接池中的最大空闲连接
          min-idle: 5       # 连接池中的最小空闲连接
#    redisson:
#      ## 注:默认序列化方式Kryo5Codec与spring statemachine依赖冲突,
#       ##使用json-jackson替代。config后的“|”代表多行文本
#      config: |
#        codec: !<org.redisson.codec.JsonJacksonCodec> {}
#        singleServerConfig:
#          password: 123456
#          address: "redis://redis:6379"
